INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('ChickenBreast','f','f','t',28.96,191,0,7.57,0,'Grams',98,'REGULAR',1);


INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Salmon','f','f','t',21.62,146,0,5.93,0,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Tuna','f','f','t',23.38,108,0,0.95,0,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Beef','f','f','t',27.29,252,0,15.01,0,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('GroundBeef','f','f','t',25.35,276,0,18.58,0,'Grams',100,'REGULAR',1);


INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Almond','t','t','t',0.26,7,0.24,0.61,0.06,'Unit',1,'REGULAR',1);


INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Tomato','t','t','t',1.08,22,4.82,0.25,3.23,'Grams',123,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('RedBellPepper','t','t','t',0.99,26,6.03,0.3,4.2,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('GreenBellPepper','t','t','t',0.86,20,4.64,0.17,2.4,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Onion','t','t','t',0.92,42,10.11,0.08,4.28,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Pumpkin','t','t','t',1,26,6.5,0.1,1.36,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('WhiteRice','t','t','t',2.66,129,27.9,0.28,0.05,'Grams',100,'REGULAR',1);


INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('BlackBeans','t','t','t',6.03,91,16.56,0.29,0,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Carrot','t','t','t',0.93,41,9.58,0.24,4.54,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Cucumber','t','t','t',0.65,15,3.63,0.11,1.67,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Spinach','t','t','t',2.89,23,3.63,0.39,0.42,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Lettuce','t','t','t',0.9,14,2.97,0.14,1.76,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Egg','f','f','t',12.58,147,0.77,9.94,0.77,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Banana','t','t','t',1.09,89,22.84,0.33,12.23,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Apple','t','t','t',0.09,18,4.83,0.06,3.64,'Units',1,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Peach','t','t','t',0.91,39,9.54,0.25,8.39,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Grapes','t','t','t',0.72,69,18.1,0.16,15.48,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Pear','t','t','t',0.38,58,15.46,0.12,9.8,'Grams',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Milk','f','f','t',3.39,52,4.86,2.06,5.32,'Milliliters',100,'REGULAR',1);

INSERT INTO ingredients(ingredient_name,
                        is_vegetarian,
                        is_vegan,
                        tacc_free,
                        protein_count,
                        calorie_count,
                        carbohydrate_count,
                        fat_count,
                        sugar_count,
                        serving_type,
                        serving,
                        ingredient_status,
                        user_id) VALUES('Chocolate','f','f','t',7.65,535,59.4,29.66,51.5,'Milliliters',100,'REGULAR',1);


